config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#index'

  get 'post' => 'posts#index', as: 'posts'
  get 'post_new' => 'posts#new', as: 'post_new'
  post 'post' => 'posts#create', as: 'post'
  get 'post_show' => 'posts#show', as: 'posts_show'
  get 'post/:id' => 'posts#show', as: 'post_show'
  get 'post/:id/edit' => 'posts#edit', as: 'post_edit'
  patch 'post/:id/update' => 'posts#update', as: 'post_update'
  delete 'post/:id/delete' => 'posts#destroy', as: 'post_delete'
  # delete 'articles/' => 'articles#destroy_all', as: 'article_delete_all'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @posts = Post.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  # def new
  #   @post = Post.new
  # end

  # def create
  #   @post = Post.new(post_params)
  #   if @post.save
  #     # flash[:notice] = "Article seve!"
  #     redirect_to posts_path
  #   else
  #     render :new
  #   end
  # end

  # def edit
  #   @post = Post.find_by_id(params[:id])
  # end

  # def update
  #   @post = Post.find_by_id(params[:id])
  #   if @post.update(post_params)
  #     redirect_to posts_path
  #   else
  #     render :edit
  #   end
  #   # render :article
  # end

  # def destroy
  #   @post = Post.find_by_url(params[:url])
  #   @comment = @post.comments(params[:article_url])
  #   @comment.destroy
  #
  #   redirect_to article_path
  # end

  # def destroy_all
  #   @posts = Post.all
  #   @posts.destroy_all
  #   redirect_to article_path
  # end


  # private
  # def post_params
  #   params.require(:post).permit(:name, :desc, :content, :image, :url, :active, :seo_key, :seo_title, :seo_desc, :alt)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/_aboutAuthor.html.erb
<div class="bd-toc-item bg-fff about_author">
  <h2><a class="bd-toc-link" href="#">About the Author </a></h2>
  <div class=" d-flex flex-column">
    <div class="media media-aside pt-2 d-flex justify-content-around">
      <%= image_tag('Layer 28.png', class: "author_foto align-self-center mr-3") %>
      <div class="media-body">
        <p class="mt-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A dolorem nam neque praesentium. Amet debitis dicta distinctio, eius eligendi incidunt nostrum perferendis placeat quasi, repellendus sint sit temporibus vitae voluptatum!</p>
      </div>
    </div>
  </div>
</div>

app/views/homes/_adventAside.html.erb
<div class="bd-toc-item bg-fff advertısement ">
  <a class="bd-toc-link" href="#">Advertısement </a>
  <div class=" d-flex flex-column wrap_post_top">
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 16.png', class: "align-self-center mr-3") %>
    </div>
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 16.png', class: "align-self-center mr-3") %>
    </div>
  </div>
</div>

app/views/homes/_archivesAside.html.erb
<div class="bd-toc-item bg-fff archıves ">
  <a class="bd-toc-link" href="#">archıves </a>
  <div class=" d-flex flex-column wrap_post_top">
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2">
      <div class="media-body">
        <a href="#"><span>October 2010</span></a>
      </div>
    </div>
  </div>
</div>

app/views/homes/_asidePost.html.erb
<div class="bd-toc-item bg-fff recent_posts">
  <a class="bd-toc-link" href="#">recent Posts</a>
  <div class=" d-flex flex-column wrap_post_top">
    <% @posts.last(4).each do |post| %>
      <div class="media media-aside pt-2">
        <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
        <div class="media-body">
          <p class="mt-0"><%= post.name %></p>
          <span>12 comments</span>
        </div>
      </div>
      <% end %>

  </div>
</div>

app/views/homes/_featuredPosts.html.erb
<div class="bd-toc-item bg-fff featured_posts">
  <% @posts.last(1).each do |post| %>
  <h2><a class="bd-toc-link" href="#"><%= post.name %> </a></h2>
  <div class="post-info d-flex justify-content-around pt-3">
    <div class="info-wrap d-flex">
      <div class="info-wrap-icon">
        <i class="fa fa-calendar" aria-hidden="true"></i>
      </div>
      <div class="info-wrap-text">
        <p><%= post.created_at %></p>
      </div>
    </div>
    <div class="info-wrap d-flex">
      <div class="info-wrap-icon">
        <i class="fa fa-user" aria-hidden="true"></i>
      </div>
      <div class="info-wrap-text">
        <p>User </p>
      </div>
    </div>
    <div class="info-wrap d-flex">
      <div class="info-wrap-icon">
        <i class="fa fa-comment" aria-hidden="true"></i>
      </div>
      <div class="info-wrap-text">
        <p>Comment </p>
      </div>
    </div>
    <div class="info-wrap d-flex">
      <div class="info-wrap-icon">
        <i class="fa fa-link" aria-hidden="true"></i>
      </div>
      <div class="info-wrap-text">
        <p>link</p>
      </div>
    </div>
  </div>
  <div class=" d-flex flex-column wrap_post_top">
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 16.png', class: "post-foto align-self-center mr-3") %>
    </div>
  </div>
  <div class="post-content">
    <p><%= post.content %></p>
  </div>
  <div class="post-info_footer d-flex pt-3">
    <div class="info-wrap d-flex">
      <div class="info-wrap-icon">
        <i class="fa fa-tag" aria-hidden="true"></i>
      </div>
      <div class="info-wrap-text">
        <p>Tag </p>
      </div>
    </div>
  </div>
    <% end %>
</div>

app/views/homes/_flickr.html.erb
<div class="bd-toc-item bg-fff flickr">
  <a class="bd-toc-link" href="#">recent Posts</a>
  <div class=" d-flex flex-wrap wrap_post_top">
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
    </div>
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
    </div>
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
    </div>
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
    </div>
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
    </div>
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
    </div>
  </div>
</div>

app/views/homes/_postCollection.html.erb
<%# @posts = Post.all %>

<%#= p @posts.to_json %>

<main class="post-collection mb-3">
  <div class="row">
    <div class="col-sm-8">
      <div class="card card_position">
        <div class="card-header">
          <%= image_tag('Layer 41.png', class: "card-img-top") %>
        </div>
        <div class="card-body card_body_position">
          <div class="card_body_content">
            <% @posts.last(1).each do |post| %>
            <h5 class="card-title"><%= post.name %></h5>
            <p class="card-text"><%= post.desc %></p>
              <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class=" d-flex flex-column wrap_post_top">
        <% @posts.last(4).reverse.each do |post| %>
        <div class="media pt-2">
          <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
          <div class="media-body">
            <p class="mt-0"><%= post.desc %></p>
          </div>
        </div>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/homes/_postFormCommit.html.erb
<div class="bd-toc-item bg-fff PostFormCommit">
  <a class="bd-toc-link" href="#">2 Responses to “Class aptent tac</a>
  <div class=" d-flex flex-column wrap_post_top">
    <div class="media media-aside pt-2">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
      <div class="media-body">
        <h3>Barney Simpler </h3>
        <p class="mt-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio earum exercitationem facilis obcaecati porro repellat sapiente sed sunt.</p>
      </div>
    </div>
    <div class="media media-aside pt-2 mb-3">
      <%= image_tag('Layer 28.png', class: "align-self-center mr-3") %>
      <div class="media-body">
        <h3>Barney Simpler </h3>
        <p class="mt-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio earum exercitationem facilis obcaecati porro repellat sapiente sed sunt.</p>
      </div>
    </div>
    <div class="media media-aside pt-2">
      <form class="w-100">
        <div class="form-group">
          <input type="name" class="form-control" placeholder="name">
        </div>
        <div class="form-group">
          <input type="email" class="form-control" placeholder="email" >
        </div>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="site">
        </div>
        <div class="form-group">
          <textarea class="form-control" placeholder="message" rows="3"></textarea>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>

  </div>
</div>

app/views/homes/_recentComment.html.erb
<div class="bd-toc-item bg-fff recent_comment">
  <a class="bd-toc-link" href="#">Recent Comme</a>
  <div class=" d-flex flex-column wrap_post_top">
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>

      </div>
    </div>
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>

      </div>
    </div>
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>

      </div>
    </div>
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>

      </div>
    </div>
  </div>
</div>

app/views/homes/_search.html.erb
<div class="bd-toc-item bg-fff search">
  <a class="bd-toc-link" href="#">search</a>
  <div class=" d-flex flex-column wrap_post_top">
    <input class="form-control" type="text" placeholder="Search" aria-label="Search">
  </div>
</div>

app/views/homes/_tagsAside.html.erb
<div class="bd-toc-item bg-fff tags">
  <a class="bd-toc-link" href="#">tags</a>
  <div class=" d-flex flex-wrap wrap_post_top">
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">C#</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Go</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Ruby</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">PHP</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Rails</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Laravel</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">HTML</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Postgres</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Gulp</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Java</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">Java Script</span></a>
      </div>
    </div>
    <div class="media media-aside mr-2 bg-tag">
      <div class="media-body">
        <a href="#"><span class="tag">R</span></a>
      </div>
    </div>

  </div>
</div>

app/views/homes/_twitter.html.erb
<div class="bd-toc-item bg-fff twıtter">
  <a class="bd-toc-link" href="#">recent Posts</a>
  <div class=" d-flex flex-column wrap_post_top">
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
        <a href="#">www.google.com</a>

      </div>
    </div>
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
        <a href="#">www.google.com</a>

      </div>
    </div>
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
        <a href="#">www.google.com</a>

      </div>
    </div>
    <div class="media media-aside pt-2">
      <div class="media-body">
        <p class="mt-0"><span>Violet:</span>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
        <a href="#">www.google.com</a>

      </div>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<%= render 'homes/postCollection' %>


<div class="row">
  <aside class="col-md-3">
    <nav class="bd-links">
      <%= render 'homes/asidePost' %>
      <%= render 'homes/asidePost' %>
      <%= render 'homes/recentComment' %>
      <%= render 'homes/flickr' %>
      <%= render 'homes/twitter' %>
    </nav>
  </aside>
  <div class="col-md-6">
    <article class="bd-links">
      <%= render 'homes/featuredPosts' %>
      <%= render 'homes/aboutAuthor' %>
      <%= render 'homes/postFormCommit' %>
    </article>
  </div>
  <aside class="col-md-3">
    <nav class="bd-links">
      <%= render 'homes/search' %>
      <%= render 'homes/asidePost' %>
      <%= render 'homes/tagsAside' %>
      <%= render 'homes/archivesAside' %>
      <%= render 'homes/adventAside' %>
    </nav>
  </aside>
</div>

app/views/layouts/_menu.html.erb
<header class="mb-3">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Posts', post_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Posts', post_path, class: "nav-link"%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "https://uk-ua.facebook.com", class: "nav-link" do  %>
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "https://www.linkedin.com/", class: "nav-link" do  %>
            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "https://twitter.com", class: "nav-link" do %>
            <i class="fa fa-twitter-square" aria-hidden="true"></i>
          <% end %>
        </li>
      </ul>
    </div>

  </nav>
  <h1 class="logo">THREEZINE</h1>
  <ul class="nav navbar-light bg-light">
    <li class="nav-item">
      <%= link_to 'Posts', post_path, class: "nav-link"%>
    </li>
    <li class="nav-item">
      <%= link_to 'Posts', post_path, class: "nav-link"%>
    </li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Threezine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <%= render 'layouts/menu' %>
  <%= yield %>




</div>






</body>
</html>

app/views/posts/_form.html.erb
<!--<pre> <%#= p @post.to_json %></pre>-->
<!--<pre> <%#= p @post.errors.to_json %></pre>-->



<% if @post.errors.any? %>
  <div class="errors">
    <h4><%= pluralize(@post.errors.count, "error") %></h4>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<%end %>

<div class="row">
  <div class="col-sm-6">
    <%= form_for @post , url: @post.new_record?  ? post_path : post_update_path(@post.id) do |f| %>
      <div class="field">
        <%= f.label "name" %> <br />
        <%= f.text_field :name, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "desc" %> <br />
        <%= f.text_field :desc, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "content" %> <br />
        <%= f.text_field :content, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "content" %> <br />
        <%= f.text_area :content, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "image" %> <br />
        <%= f.text_field :image, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "url" %> <br />
        <%= f.text_field :url, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "active" %> <br />
        <%= f.check_box :active, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "seo_key" %> <br />
        <%= f.text_field :seo_key, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "seo_title" %> <br />
        <%= f.text_field :seo_title, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "seo_desc" %> <br />
        <%= f.text_field :seo_desc, :class => 'form-control'%>
      </div>
      <div class="field">
        <%= f.label "alt" %> <br />
        <%= f.text_field :alt, :class => 'form-control'%>
      </div>
      <div class="field">
          <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
            Save
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1 class="text-center">Post page</h1>

app/views/posts/new.html.erb
<h1 class="text-center">create post</h1>

<%= render 'posts/form' %>

<%#= form_for @article , url: article_path do |f| %>
<!--  <p> name <%#= f.text_field :name %><br /></p>-->
<!--  <p> url <%#= f.text_field :url %><br /></p>-->
<!--  <p> title<%#= f.text_field :text %><br /></p>-->






<%#= f.submit "save"%>
<%# end %>

app/views/posts/show.html.erb
<%= @post.name %>
<%= @post.desc %>
<%= @post.content %>
<%= @post.image %>
<%= @post.active %>
<%= @post.seo_key %>
<%= @post.seo_title %>
<%= @post.seo_desc %>
<%= @post.alt %>